import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

function calculateMaturityPhase(vintage: number | null, windowStart: number, windowEnd: number): string {
  if (!vintage) return 'young'
  const currentYear = 2026
  const age = currentYear - vintage
  const peakStart = windowStart
  const peakEnd = windowEnd
  const totalLife = peakEnd + Math.round((peakEnd - peakStart) * 0.5)

  if (age < peakStart * 0.6) return 'young'
  if (age < peakStart) return 'maturing'
  if (age <= peakEnd) return 'peak'
  if (age <= totalLife) return 'declining'
  return 'declining'
}

const wines = [
  // RED WINES
  {
    name: 'Château Margaux 2015',
    producer: 'Château Margaux',
    region: 'Margaux, Bordeaux',
    country: 'France',
    grape: 'Cabernet Sauvignon blend',
    vintage: 2015,
    type: 'red',
    tastVector: { acidity: 0.6, tannin: 0.8, fruit: 0.7, sweetness: 0.1, body: 0.8, style: 0.2 },
    drinkingWindowStart: 2030,
    drinkingWindowEnd: 2055,
    storagePotential: 40,
    foodPairings: ['Grilled Lamb', 'Beef Tenderloin', 'Aged Cheese', 'Duck Confit'],
  },
  {
    name: 'Barolo Monfortino 2013',
    producer: 'Giacomo Conterno',
    region: 'Piedmont',
    country: 'Italy',
    grape: 'Nebbiolo',
    vintage: 2013,
    type: 'red',
    tastVector: { acidity: 0.8, tannin: 0.9, fruit: 0.5, sweetness: 0.05, body: 0.8, style: 0.2 },
    drinkingWindowStart: 2028,
    drinkingWindowEnd: 2050,
    storagePotential: 35,
    foodPairings: ['Truffle Risotto', 'Braised Beef', 'Wild Mushrooms', 'Parmigiano Reggiano'],
  },
  {
    name: 'Opus One 2018',
    producer: 'Opus One Winery',
    region: 'Napa Valley',
    country: 'USA',
    grape: 'Cabernet Sauvignon blend',
    vintage: 2018,
    type: 'red',
    tastVector: { acidity: 0.5, tannin: 0.7, fruit: 0.8, sweetness: 0.15, body: 0.85, style: 0.15 },
    drinkingWindowStart: 2026,
    drinkingWindowEnd: 2045,
    storagePotential: 30,
    foodPairings: ['Ribeye Steak', 'Roasted Lamb', 'Dark Chocolate', 'Grilled Portobello'],
  },
  {
    name: 'Malbec Reserva',
    producer: 'Catena Zapata',
    region: 'Mendoza',
    country: 'Argentina',
    grape: 'Malbec',
    vintage: 2020,
    type: 'red',
    tastVector: { acidity: 0.5, tannin: 0.6, fruit: 0.85, sweetness: 0.15, body: 0.75, style: 0.15 },
    drinkingWindowStart: 2024,
    drinkingWindowEnd: 2032,
    storagePotential: 12,
    foodPairings: ['Grilled Steak', 'Empanadas', 'Blue Cheese', 'Barbecue Ribs'],
  },
  {
    name: 'Chianti Classico Riserva',
    producer: 'Fontodi',
    region: 'Tuscany',
    country: 'Italy',
    grape: 'Sangiovese',
    vintage: 2019,
    type: 'red',
    tastVector: { acidity: 0.75, tannin: 0.65, fruit: 0.6, sweetness: 0.1, body: 0.7, style: 0.2 },
    drinkingWindowStart: 2025,
    drinkingWindowEnd: 2035,
    storagePotential: 15,
    foodPairings: ['Pasta Bolognese', 'Grilled Vegetables', 'Pecorino', 'Pizza Margherita'],
  },
  {
    name: 'Pinot Noir Willamette',
    producer: 'Domaine Drouhin',
    region: 'Willamette Valley',
    country: 'USA',
    grape: 'Pinot Noir',
    vintage: 2021,
    type: 'red',
    tastVector: { acidity: 0.7, tannin: 0.3, fruit: 0.7, sweetness: 0.1, body: 0.4, style: 0.2 },
    drinkingWindowStart: 2024,
    drinkingWindowEnd: 2031,
    storagePotential: 10,
    foodPairings: ['Roasted Chicken', 'Salmon', 'Mushroom Risotto', 'Gruyère'],
  },
  {
    name: 'Amarone della Valpolicella',
    producer: 'Allegrini',
    region: 'Veneto',
    country: 'Italy',
    grape: 'Corvina blend',
    vintage: 2018,
    type: 'red',
    tastVector: { acidity: 0.4, tannin: 0.7, fruit: 0.8, sweetness: 0.3, body: 0.95, style: 0.15 },
    drinkingWindowStart: 2026,
    drinkingWindowEnd: 2040,
    storagePotential: 25,
    foodPairings: ['Braised Short Ribs', 'Aged Gouda', 'Wild Boar', 'Osso Buco'],
  },
  {
    name: 'Rioja Gran Reserva',
    producer: 'López de Heredia',
    region: 'Rioja',
    country: 'Spain',
    grape: 'Tempranillo',
    vintage: 2011,
    type: 'red',
    tastVector: { acidity: 0.65, tannin: 0.5, fruit: 0.4, sweetness: 0.1, body: 0.6, style: 0.3 },
    drinkingWindowStart: 2024,
    drinkingWindowEnd: 2036,
    storagePotential: 25,
    foodPairings: ['Lamb Chops', 'Manchego', 'Paella', 'Chorizo'],
  },
  {
    name: 'Syrah Côte-Rôtie',
    producer: 'E. Guigal',
    region: 'Northern Rhône',
    country: 'France',
    grape: 'Syrah',
    vintage: 2019,
    type: 'red',
    tastVector: { acidity: 0.55, tannin: 0.7, fruit: 0.65, sweetness: 0.1, body: 0.8, style: 0.25 },
    drinkingWindowStart: 2027,
    drinkingWindowEnd: 2040,
    storagePotential: 22,
    foodPairings: ['Venison', 'Beef Stew', 'Black Olive Tapenade', 'Roquefort'],
  },
  {
    name: 'Zinfandel Old Vine',
    producer: 'Ridge Vineyards',
    region: 'Sonoma County',
    country: 'USA',
    grape: 'Zinfandel',
    vintage: 2020,
    type: 'red',
    tastVector: { acidity: 0.5, tannin: 0.55, fruit: 0.9, sweetness: 0.2, body: 0.75, style: 0.2 },
    drinkingWindowStart: 2024,
    drinkingWindowEnd: 2032,
    storagePotential: 12,
    foodPairings: ['Barbecue Ribs', 'Pizza', 'Spicy Sausage', 'Cheddar'],
  },

  // WHITE WINES
  {
    name: 'Chablis Grand Cru Les Clos',
    producer: 'Domaine William Fèvre',
    region: 'Chablis, Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    vintage: 2020,
    type: 'white',
    tastVector: { acidity: 0.85, tannin: 0.05, fruit: 0.4, sweetness: 0.05, body: 0.5, style: 0.15 },
    drinkingWindowStart: 2025,
    drinkingWindowEnd: 2035,
    storagePotential: 15,
    foodPairings: ['Oysters', 'Lobster', 'Grilled Fish', 'Goat Cheese'],
  },
  {
    name: 'Sauvignon Blanc',
    producer: 'Cloudy Bay',
    region: 'Marlborough',
    country: 'New Zealand',
    grape: 'Sauvignon Blanc',
    vintage: 2023,
    type: 'white',
    tastVector: { acidity: 0.9, tannin: 0.0, fruit: 0.75, sweetness: 0.1, body: 0.3, style: 0.1 },
    drinkingWindowStart: 2024,
    drinkingWindowEnd: 2027,
    storagePotential: 5,
    foodPairings: ['Salad', 'Sushi', 'Goat Cheese', 'Asparagus'],
  },
  {
    name: 'Riesling Smaragd',
    producer: 'F.X. Pichler',
    region: 'Wachau',
    country: 'Austria',
    grape: 'Riesling',
    vintage: 2021,
    type: 'white',
    tastVector: { acidity: 0.85, tannin: 0.0, fruit: 0.6, sweetness: 0.15, body: 0.45, style: 0.15 },
    drinkingWindowStart: 2025,
    drinkingWindowEnd: 2036,
    storagePotential: 15,
    foodPairings: ['Sushi', 'Thai Curry', 'Pork Schnitzel', 'Spicy Asian Food'],
  },
  {
    name: 'Meursault Premier Cru',
    producer: 'Domaine Roulot',
    region: 'Burgundy',
    country: 'France',
    grape: 'Chardonnay',
    vintage: 2020,
    type: 'white',
    tastVector: { acidity: 0.6, tannin: 0.05, fruit: 0.5, sweetness: 0.1, body: 0.7, style: 0.2 },
    drinkingWindowStart: 2025,
    drinkingWindowEnd: 2035,
    storagePotential: 15,
    foodPairings: ['Lobster Thermidor', 'Roasted Chicken', 'Comté', 'Cream Pasta'],
  },
  {
    name: 'Gewürztraminer Grand Cru',
    producer: 'Trimbach',
    region: 'Alsace',
    country: 'France',
    grape: 'Gewürztraminer',
    vintage: 2019,
    type: 'white',
    tastVector: { acidity: 0.4, tannin: 0.05, fruit: 0.8, sweetness: 0.45, body: 0.65, style: 0.15 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2032,
    storagePotential: 12,
    foodPairings: ['Thai Curry', 'Foie Gras', 'Munster Cheese', 'Spicy Asian Food'],
  },
  {
    name: 'Albariño Rias Baixas',
    producer: 'Pazo de Señorans',
    region: 'Galicia',
    country: 'Spain',
    grape: 'Albariño',
    vintage: 2022,
    type: 'white',
    tastVector: { acidity: 0.8, tannin: 0.0, fruit: 0.6, sweetness: 0.1, body: 0.35, style: 0.1 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2027,
    storagePotential: 5,
    foodPairings: ['Seafood', 'Grilled Shrimp', 'Ceviche', 'Light Salad'],
  },
  {
    name: 'Viognier Condrieu',
    producer: 'E. Guigal',
    region: 'Northern Rhône',
    country: 'France',
    grape: 'Viognier',
    vintage: 2021,
    type: 'white',
    tastVector: { acidity: 0.35, tannin: 0.05, fruit: 0.85, sweetness: 0.2, body: 0.7, style: 0.15 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2030,
    storagePotential: 8,
    foodPairings: ['Roasted Chicken', 'Lobster', 'Creamy Pasta', 'Soft Cheese'],
  },
  {
    name: 'Grüner Veltliner Federspiel',
    producer: 'Domäne Wachau',
    region: 'Wachau',
    country: 'Austria',
    grape: 'Grüner Veltliner',
    vintage: 2022,
    type: 'white',
    tastVector: { acidity: 0.75, tannin: 0.0, fruit: 0.5, sweetness: 0.1, body: 0.35, style: 0.1 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2027,
    storagePotential: 5,
    foodPairings: ['Wiener Schnitzel', 'Salad', 'Sushi', 'Light Fish'],
  },

  // ROSÉ
  {
    name: 'Whispering Angel',
    producer: 'Château d\'Esclans',
    region: 'Provence',
    country: 'France',
    grape: 'Grenache blend',
    vintage: 2023,
    type: 'rosé',
    tastVector: { acidity: 0.65, tannin: 0.05, fruit: 0.6, sweetness: 0.15, body: 0.3, style: 0.1 },
    drinkingWindowStart: 2024,
    drinkingWindowEnd: 2025,
    storagePotential: 2,
    foodPairings: ['Grilled Shrimp', 'Salad Niçoise', 'Light Pasta', 'Fresh Fruit'],
  },
  {
    name: 'Rosé de Bandol',
    producer: 'Domaine Tempier',
    region: 'Bandol, Provence',
    country: 'France',
    grape: 'Mourvèdre blend',
    vintage: 2022,
    type: 'rosé',
    tastVector: { acidity: 0.7, tannin: 0.1, fruit: 0.5, sweetness: 0.1, body: 0.4, style: 0.2 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2026,
    storagePotential: 3,
    foodPairings: ['Grilled Fish', 'Bouillabaisse', 'Tapenade', 'Mediterranean Salad'],
  },
  {
    name: 'Tavel Rosé',
    producer: 'Domaine de la Mordorée',
    region: 'Southern Rhône',
    country: 'France',
    grape: 'Grenache blend',
    vintage: 2022,
    type: 'rosé',
    tastVector: { acidity: 0.6, tannin: 0.15, fruit: 0.65, sweetness: 0.1, body: 0.5, style: 0.15 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2026,
    storagePotential: 3,
    foodPairings: ['Grilled Chicken', 'Charcuterie', 'Roasted Vegetables', 'Paella'],
  },

  // SPARKLING
  {
    name: 'Dom Pérignon 2012',
    producer: 'Moët & Chandon',
    region: 'Champagne',
    country: 'France',
    grape: 'Chardonnay/Pinot Noir',
    vintage: 2012,
    type: 'sparkling',
    tastVector: { acidity: 0.85, tannin: 0.05, fruit: 0.55, sweetness: 0.1, body: 0.55, style: 0.15 },
    drinkingWindowStart: 2025,
    drinkingWindowEnd: 2040,
    storagePotential: 20,
    foodPairings: ['Oysters', 'Caviar', 'Lobster', 'Aged Parmesan'],
  },
  {
    name: 'Franciacorta Satèn',
    producer: 'Ca\' del Bosco',
    region: 'Lombardy',
    country: 'Italy',
    grape: 'Chardonnay',
    vintage: 2018,
    type: 'sparkling',
    tastVector: { acidity: 0.75, tannin: 0.0, fruit: 0.5, sweetness: 0.15, body: 0.4, style: 0.1 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2030,
    storagePotential: 10,
    foodPairings: ['Risotto', 'Fresh Seafood', 'Bruschetta', 'Light Appetizers'],
  },
  {
    name: 'Prosecco Superiore',
    producer: 'Bisol',
    region: 'Valdobbiadene',
    country: 'Italy',
    grape: 'Glera',
    vintage: 2023,
    type: 'sparkling',
    tastVector: { acidity: 0.6, tannin: 0.0, fruit: 0.7, sweetness: 0.3, body: 0.25, style: 0.05 },
    drinkingWindowStart: 2024,
    drinkingWindowEnd: 2025,
    storagePotential: 2,
    foodPairings: ['Prosciutto', 'Light Appetizers', 'Fresh Fruit', 'Bruschetta'],
  },
  {
    name: 'Crémant d\'Alsace',
    producer: 'Domaine Weinbach',
    region: 'Alsace',
    country: 'France',
    grape: 'Pinot Blanc blend',
    vintage: 2021,
    type: 'sparkling',
    tastVector: { acidity: 0.7, tannin: 0.0, fruit: 0.5, sweetness: 0.15, body: 0.35, style: 0.1 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2027,
    storagePotential: 5,
    foodPairings: ['Quiche', 'Soft Cheese', 'Light Fish', 'Fresh Fruit'],
  },

  // NATURAL/ORANGE WINES
  {
    name: 'Gut Oggau Theodora',
    producer: 'Gut Oggau',
    region: 'Burgenland',
    country: 'Austria',
    grape: 'Grüner Veltliner/Welschriesling',
    vintage: 2021,
    type: 'white',
    tastVector: { acidity: 0.7, tannin: 0.2, fruit: 0.4, sweetness: 0.05, body: 0.5, style: 0.85 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2028,
    storagePotential: 7,
    foodPairings: ['Charcuterie', 'Roasted Vegetables', 'Aged Cheese', 'Grilled Fish'],
  },
  {
    name: 'Radikon Ribolla Gialla',
    producer: 'Radikon',
    region: 'Friuli',
    country: 'Italy',
    grape: 'Ribolla Gialla',
    vintage: 2017,
    type: 'white',
    tastVector: { acidity: 0.65, tannin: 0.35, fruit: 0.35, sweetness: 0.05, body: 0.6, style: 0.9 },
    drinkingWindowStart: 2023,
    drinkingWindowEnd: 2032,
    storagePotential: 15,
    foodPairings: ['Pork Belly', 'Aged Cheese', 'Rich Pasta', 'Middle Eastern Food'],
  },

  // DESSERT
  {
    name: 'Sauternes Premier Cru',
    producer: 'Château Suduiraut',
    region: 'Sauternes, Bordeaux',
    country: 'France',
    grape: 'Sémillon/Sauvignon Blanc',
    vintage: 2018,
    type: 'white',
    tastVector: { acidity: 0.7, tannin: 0.0, fruit: 0.8, sweetness: 0.9, body: 0.7, style: 0.1 },
    drinkingWindowStart: 2028,
    drinkingWindowEnd: 2060,
    storagePotential: 50,
    foodPairings: ['Foie Gras', 'Blue Cheese', 'Crème Brûlée', 'Fruit Tart'],
  },
  {
    name: 'Tokaji Aszú 5 Puttonyos',
    producer: 'Royal Tokaji',
    region: 'Tokaj',
    country: 'Hungary',
    grape: 'Furmint',
    vintage: 2017,
    type: 'white',
    tastVector: { acidity: 0.8, tannin: 0.0, fruit: 0.75, sweetness: 0.85, body: 0.65, style: 0.15 },
    drinkingWindowStart: 2025,
    drinkingWindowEnd: 2055,
    storagePotential: 40,
    foodPairings: ['Foie Gras', 'Blue Cheese', 'Apricot Desserts', 'Dark Chocolate'],
  },
  {
    name: 'Moscato d\'Asti',
    producer: 'Paolo Saracco',
    region: 'Piedmont',
    country: 'Italy',
    grape: 'Moscato',
    vintage: 2023,
    type: 'sparkling',
    tastVector: { acidity: 0.5, tannin: 0.0, fruit: 0.85, sweetness: 0.7, body: 0.2, style: 0.05 },
    drinkingWindowStart: 2024,
    drinkingWindowEnd: 2025,
    storagePotential: 2,
    foodPairings: ['Fresh Fruit', 'Light Desserts', 'Almond Cake', 'Biscotti'],
  },
]

async function main() {
  console.log('Clearing existing wines...')
  await prisma.feedback.deleteMany()
  await prisma.scan.deleteMany()
  await prisma.wine.deleteMany()

  console.log('Seeding wines...')

  for (const wine of wines) {
    const maturityPhase = calculateMaturityPhase(
      wine.vintage,
      wine.drinkingWindowStart,
      wine.drinkingWindowEnd
    )

    await prisma.wine.create({
      data: {
        name: wine.name,
        producer: wine.producer,
        region: wine.region,
        country: wine.country,
        grape: wine.grape,
        vintage: wine.vintage,
        type: wine.type,
        tastVector: JSON.stringify(wine.tastVector),
        drinkingWindowStart: wine.drinkingWindowStart,
        drinkingWindowEnd: wine.drinkingWindowEnd,
        maturityPhase,
        storagePotential: wine.storagePotential,
        foodPairings: JSON.stringify(wine.foodPairings),
      },
    })
  }

  console.log(`Seeded ${wines.length} wines`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
